sudo: required
services:
  - docker

before_install:
  - docker build -t karljgriffin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true karljgriffin/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "frontend"
  env: "Frontend-env-1"
  bucket_name: "elasticbeanstalk-eu-west-1-191095130461"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"